# Generated by Django 3.2.8 on 2021-11-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquirysource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('joindate', models.DateField()),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=100)),
                ('idnumber', models.CharField(max_length=100)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.designation')),
            ],
        ),
        migrations.CreateModel(
            name='StuRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('regDate', models.DateField()),
                ('totalfee', models.IntegerField()),
                ('discountfee', models.IntegerField()),
                ('paymentRefNo', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('regStatus', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('clgName', models.CharField(max_length=100)),
                ('highQualification', models.CharField(max_length=100)),
                ('enquiryDate', models.DateField()),
                ('pfdj', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('enqsrcId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.enquirysource')),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedate', models.DateField()),
                ('totalfee', models.IntegerField()),
                ('installment', models.CharField(max_length=100)),
                ('discountfee', models.IntegerField()),
                ('submitedfee', models.IntegerField()),
                ('remainingfee', models.IntegerField()),
                ('paymentRefNo', models.CharField(max_length=100)),
                ('receiptNo', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('paymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.payment')),
                ('regId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.sturegistration')),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
            ],
        ),
    ]
